kind: pipeline
name: default

steps:
- name: build-font
  image: fanux/store-font:dev
  commands:
     - cd font
     - npm build

- name: publish-font
  image: plugins/docker
  settings:
    repo: fanux/store-font
    tags: ${DRONE_TAG=latest}
    username: fanux
    password:
      from_secret: docker-hub-pass

- name: deploy-back
  image: lachlanevenson/k8s-kubectl
  commands:
    - mkdir ~/.kube
    - cp deploy/config ~/.kube/config
    - kubectl delete -f deploy/store-back.yaml || true
    - kubectl create -f deploy/store-back.yaml || true

