kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    store: back 
  name: store-back
spec:
    metadata:
      labels:
        store: back 
    spec:
      containers:
      - name: store-back
        image: fanux/store-back:latest
        imagePullPolicy: Always
      hostNetwork: true
